name: Publish Artifacts to GitHub Packages

on: 
  push

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Publish Package
        run: mvn --batch-mode deploy -e -X

        env:
          GITHUB_TOKEN: ${{ secrets.JAVA_TOKEN }}
